services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: devops
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nestjs:
    build:
      dockerfile: Dockerfile
    container_name: api-nestjs
    depends_on:
      - postgres
    ports:
      - "3005:3005"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
